//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int Id { get; set; }
        public Nullable<int> Id_Clientes_Tipo { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Dni { get; set; }
        public string Cuit { get; set; }
        public string Domicilio_1 { get; set; }
        public string Domicilio_2 { get; set; }
        public string Domicilio_3 { get; set; }
        public string Telefono_Comercial { get; set; }
        public string Telefono_Particular { get; set; }
        public string Representante { get; set; }
        public string Representante_Cuit { get; set; }
        public bool Afip_Monotributo { get; set; }
        public bool Afip_Empleador { get; set; }
        public bool Afip_Regimen_Gral { get; set; }
        public bool Impuestos_Ing_Brutos { get; set; }
        public bool Impuestos_Conv_Multi { get; set; }
        public bool Tasas_Municipales { get; set; }
        public int Id_Metodo_Facturacion { get; set; }
        public bool Activo { get; set; }
    }
}
