//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int Id { get; set; }
        public string Variable { get; set; }
        public string Valor_C { get; set; }
        public Nullable<int> Valor_N { get; set; }
        public Nullable<decimal> Valor_D { get; set; }
        public string Descripcion { get; set; }
    }
}
