//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public int Id { get; set; }
        public Nullable<int> Id_Provincia { get; set; }
        public Nullable<int> Codigo_Afip { get; set; }
        public string Descripcion { get; set; }
        public bool Borrado { get; set; }
    }
}
