//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Tareas_Tipo { get; set; }
        public int Id_Tareas_Estado { get; set; }
        public int Id_Usuario { get; set; }
        public int Mes { get; set; }
        public int Año { get; set; }
        public string Observacion { get; set; }
        public bool Borrado { get; set; }
    }
}
